package com.fongmi.btengine;

import android.util.Log;

import org.libtorrent4j.AddTorrentParams;
import org.libtorrent4j.Priority;
import org.libtorrent4j.SessionManager;
import org.libtorrent4j.Sha1Hash;
import org.libtorrent4j.TorrentHandle;
import org.libtorrent4j.TorrentInfo;
import org.libtorrent4j.TorrentStatus;
import org.libtorrent4j.swig.error_code;
import org.libtorrent4j.swig.libtorrent;
import org.libtorrent4j.swig.string_vector;
import org.libtorrent4j.swig.torrent_flags_t;

import java.io.File;
import java.util.Arrays;

/**
 * libtorrent4j magnet/torrent client.
 * Replaces the old aria2 JSON-RPC client with direct libtorrent4j API calls.
 * Supports magnet link resolution and sequential downloading for streaming.
 */
public class LibtorrentSession {

    private static final String TAG = LibtorrentSession.class.getSimpleName();
    private static final int META_DATA_TIMEOUT_SECONDS = 30;
    private static final int DOWNLOAD_TIMEOUT_SECONDS = 120;

    private final SessionManager session;

    public LibtorrentSession() {
        this.session = LibtorrentEngine.get().getSession();
    }

    /**
     * Add a magnet link and wait for metadata to be received.
     * Returns the info hash as a string identifier.
     */
    public String addMagnet(String magnetUri) throws Exception {
        if (session == null || !session.isRunning()) {
            throw new IllegalStateException("libtorrent4j session is not running");
        }

        Log.e(TAG, "Adding magnet: " + magnetUri);

        // Handle non-standard magnet URIs (e.g. magnet:///data/...torrent?...name=...&index=0)
        // These are generated by Thunder when it downloads a .torrent file from a magnet link.
        // libtorrent4j's parseMagnetUri expects standard "magnet:?xt=urn:btih:..." format.
        String actualMagnetUri = magnetUri;
        if (magnetUri.startsWith("magnet://")) {
            // Try to extract a real magnet link from query parameters, or convert to standard format
            android.net.Uri uri = android.net.Uri.parse(magnetUri);
            String name = uri.getQueryParameter("name");
            if (name != null && uri.getPath() != null && uri.getPath().endsWith(".torrent")) {
                // This is a local .torrent file path, not a magnet link
                // We need to add it as a torrent file instead
                Log.e(TAG, "URL is a local torrent file, not a magnet link: " + magnetUri);
                // Try to add as torrent file
                File torrentFile = new File(uri.getPath());
                if (torrentFile.exists()) {
                    return addTorrentFile(torrentFile, name);
                }
                throw new IllegalArgumentException("Torrent file not found: " + uri.getPath());
            }
            // Otherwise, try to use it as-is (might still work)
            Log.e(TAG, "Non-standard magnet URI, trying as-is: " + magnetUri);
        }

        // Parse the magnet URI to get add_torrent_params
        AddTorrentParams params = AddTorrentParams.parseMagnetUri(actualMagnetUri);
        if (params == null) {
            throw new IllegalArgumentException("Invalid magnet URI: " + actualMagnetUri);
        }

        // Set save path
        File saveDir = new File(com.github.catvod.Init.context().getCacheDir(), "libtorrent/downloads");
        if (!saveDir.exists()) saveDir.mkdirs();
        params.setSavePath(saveDir.getAbsolutePath());

        // Set sequential download flag for streaming
        torrent_flags_t flags = params.getFlags();
        flags = flags.or_(libtorrent.getSequential_download());
        params.setFlags(flags);

        // Preset trackers via add_torrent_params (reference: libretorrent addDefaultTrackers)
        // Ensures all trackers are active before the first announce request,
        // unlike torrent_handle.add_tracker() which misses the initial announce.
        // Combined with session-level announce_to_all_trackers=true, all trackers
        // receive announce requests simultaneously for maximum peer discovery.
        String[] trackerArray = LibtorrentEngine.getTrackers();
        string_vector trackers = new string_vector();
        trackers.addAll(Arrays.asList(trackerArray));
        params.swig().setTrackers(trackers);
        Log.e(TAG, "Trackers preset: " + trackerArray.length + " trackers, announce_to_all="
            + LibtorrentEngine.announceToAllEnabled());

        // Add the torrent via the native session and get the handle
        error_code ec = new error_code();
        org.libtorrent4j.swig.torrent_handle nativeHandle = session.swig().add_torrent(params.swig(), ec);
        if (ec.value() != 0) {
            throw new IllegalStateException("Failed to add torrent: " + ec.message());
        }

        TorrentHandle handle = new TorrentHandle(nativeHandle);

        // Wait for metadata to be received by polling
        long startTime = System.currentTimeMillis();
        Sha1Hash infoHash = null;

        while (System.currentTimeMillis() - startTime < META_DATA_TIMEOUT_SECONDS * 1000L) {
            if (handle.isValid()) {
                TorrentStatus status = handle.status();
                if (status != null && status.hasMetadata()) {
                    TorrentInfo ti = handle.torrentFile();
                    if (ti != null && ti.isValid()) {
                        infoHash = ti.infoHash();
                        Log.e(TAG, "Metadata received, infoHash: " + infoHash.toHex());
                        // Set file priorities for streaming: only download the first file,
                        // skip all others to save bandwidth (reference: libretorrent prioritizeFiles)
                        prioritizeForStreaming(handle, ti);
                        break;
                    }
                }
            }
            Thread.sleep(200);
        }

        if (infoHash == null) {
            Log.e(TAG, "Timeout waiting for metadata from: " + magnetUri);
            // Remove the torrent if metadata not received
            try { session.swig().remove_torrent(nativeHandle); } catch (Exception ignored) {}
            return null;
        }

        return infoHash.toHex();
    }

    /**
     * Add a local .torrent file and wait for it to be ready.
     * Returns the info hash as a string identifier.
     */
    public String addTorrentFile(File torrentFile, String selectedFileName) throws Exception {
        if (session == null || !session.isRunning()) {
            throw new IllegalStateException("libtorrent4j session is not running");
        }

        Log.e(TAG, "Adding torrent file: " + torrentFile.getAbsolutePath());

        // Load the torrent info from the .torrent file
        TorrentInfo ti = new TorrentInfo(torrentFile);
        if (ti == null || !ti.isValid()) {
            throw new IllegalArgumentException("Invalid torrent file: " + torrentFile);
        }

        Log.e(TAG, "Torrent info loaded: " + ti.name() + ", files: " + ti.numFiles());

        // Create add_torrent_params and set the torrent info
        AddTorrentParams params = new AddTorrentParams();
        params.setTorrentInfo(ti);

        // Set save path
        File saveDir = new File(com.github.catvod.Init.context().getCacheDir(), "libtorrent/downloads");
        if (!saveDir.exists()) saveDir.mkdirs();
        params.setSavePath(saveDir.getAbsolutePath());

        // Set sequential download flag for streaming
        torrent_flags_t flags = params.getFlags();
        flags = flags.or_(libtorrent.getSequential_download());
        params.setFlags(flags);

        // Preset trackers via add_torrent_params (same as addMagnet)
        string_vector trackers = new string_vector();
        trackers.addAll(Arrays.asList(LibtorrentEngine.getTrackers()));
        params.swig().setTrackers(trackers);

        // Add the torrent via the native session and get the handle
        error_code ec = new error_code();
        org.libtorrent4j.swig.torrent_handle nativeHandle = session.swig().add_torrent(params.swig(), ec);
        if (ec.value() != 0) {
            throw new IllegalStateException("Failed to add torrent file: " + ec.message());
        }

        TorrentHandle handle = new TorrentHandle(nativeHandle);

        // Get the info hash directly from TorrentInfo (already loaded from file)
        Sha1Hash infoHash = ti.infoHash();
        Log.e(TAG, "Torrent file added, infoHash: " + infoHash.toHex() + ", name: " + ti.name());

        // Set file priorities for streaming: only download the first file
        prioritizeForStreaming(handle, ti);

        return infoHash.toHex();
    }

    /**
     * Wait for a file to be available for streaming.
     * Returns the file path when at least some data is downloaded.
     */
    public String waitForFile(String infoHash) throws Exception {
        if (session == null || !session.isRunning()) {
            throw new IllegalStateException("libtorrent4j session is not running");
        }

        // Find the torrent handle by info hash
        TorrentHandle handle = findTorrent(infoHash);
        if (handle == null) {
            throw new IllegalStateException("Torrent not found: " + infoHash);
        }

        // Log initial status
        TorrentStatus initialStatus = handle.status();
        if (initialStatus != null) {
            Log.e(TAG, "Initial status: state=" + initialStatus.state()
                + ", hasMetadata=" + initialStatus.hasMetadata()
                + ", totalWanted=" + initialStatus.totalWanted()
                + ", totalDone=" + initialStatus.totalDone()
                + ", numPeers=" + initialStatus.numPeers()
                + ", numSeeds=" + initialStatus.numSeeds()
                + ", listPeers=" + initialStatus.listPeers()
                + ", listSeeds=" + initialStatus.listSeeds()
                + ", downloadRate=" + initialStatus.downloadRate()
                + ", uploadRate=" + initialStatus.uploadRate()
                + ", progress=" + initialStatus.progress());
        }

        // First, try to get the file path from metadata immediately (for .torrent files)
        // For local .torrent files, metadata is already available
        try {
            TorrentStatus status = handle.status();
            if (status != null && status.hasMetadata()) {
                TorrentInfo ti = handle.torrentFile();
                if (ti != null && ti.isValid() && ti.numFiles() > 0) {
                    // Get the file name (not full path) to avoid double directory nesting
                    // filePath(savePath) returns savePath + torrent_name + file_name
                    // fileName() returns just the file name
                    String fileName = ti.files().fileName(0);
                    // The actual save path set in addTorrentFile is: /cache/libtorrent/downloads
                    // libtorrent will create: /cache/libtorrent/downloads/torrent_name/file_name
                    File saveDir = new File(com.github.catvod.Init.context().getCacheDir(), "libtorrent/downloads");
                    File torrentDir = new File(saveDir, ti.name());
                    File fullPath = new File(torrentDir, fileName);
                    Log.e(TAG, "Metadata available, expected file: " + fullPath.getAbsolutePath());
                    
                    // If file already exists with data AND first piece is downloaded, return immediately
                    // Checking havePiece(0) ensures the player can read valid data from the start
                    if (fullPath.exists() && fullPath.length() > 0 && handle.havePiece(0)) {
                        Log.e(TAG, "File already available: " + fullPath.getAbsolutePath() + " (" + fullPath.length() + " bytes)");
                        return fullPath.getAbsolutePath();
                    }

                    // File doesn't exist yet, but we know the path - wait for it
                    Log.e(TAG, "Waiting for file to be created: " + fullPath.getAbsolutePath());
                    long startTime = System.currentTimeMillis();
                    long lastLogTime = 0;
                    int loopCount = 0;
                    while (System.currentTimeMillis() - startTime < DOWNLOAD_TIMEOUT_SECONDS * 1000L) {
                        if (!handle.isValid()) {
                            Log.e(TAG, "Torrent handle became invalid while waiting");
                            return null;
                        }

                        // Check if first piece is downloaded - this is more reliable than
                        // just checking file existence, as it guarantees valid data is available
                        if (handle.havePiece(0)) {
                            Log.e(TAG, "First piece downloaded, file available: " + fullPath.getAbsolutePath()
                                + " (exists=" + fullPath.exists() + ", length=" + fullPath.length() + ")");
                            return fullPath.getAbsolutePath();
                        }

                        // Fallback: check if file exists with data (for pre-allocated files)
                        if (fullPath.exists() && fullPath.length() > 0) {
                            Log.e(TAG, "File exists but first piece not done yet, waiting for piece 0...");
                        }
                        
                        // Get current status for progress tracking
                        TorrentStatus currentStatus = handle.status();
                        if (currentStatus != null) {
                            long downloaded = currentStatus.totalDone();
                            long total = currentStatus.totalWanted();
                            int numPeers = currentStatus.numPeers();
                            int numSeeds = currentStatus.numSeeds();
                            int listPeers = currentStatus.listPeers();
                            int listSeeds = currentStatus.listSeeds();
                            long downloadRate = currentStatus.downloadRate();
                            
                            // Log progress every 2 seconds
                            long now = System.currentTimeMillis();
                            if (now - lastLogTime > 2000) {
                                lastLogTime = now;
                                if (total > 0) {
                                    int pct = (int)(downloaded * 100 / total);
                                    Log.e(TAG, "Download progress: " + pct + "% (" + downloaded + "/" + total + " bytes)"
                                        + ", state: " + currentStatus.state()
                                        + ", peers: " + numPeers + "/" + listPeers
                                        + ", seeds: " + numSeeds + "/" + listSeeds
                                        + ", rate: " + downloadRate + " bytes/s");
                                } else {
                                    Log.e(TAG, "Download state: " + currentStatus.state()
                                        + ", peers: " + numPeers + "/" + listPeers
                                        + ", seeds: " + numSeeds + "/" + listSeeds
                                        + ", rate: " + downloadRate + " bytes/s");
                                }
                                // Also log file existence check
                                Log.e(TAG, "File check: exists=" + fullPath.exists() + ", length=" + fullPath.length()
                                    + ", elapsed=" + (now - startTime)/1000 + "s");
                            }
                            
                            // If downloading and has some progress, check if first piece is done
                            if (currentStatus.state() == TorrentStatus.State.DOWNLOADING && downloaded > 0) {
                                // Only return when first piece is actually downloaded
                                if (handle.havePiece(0)) {
                                    Log.e(TAG, "First piece done after download started: " + fullPath.getAbsolutePath());
                                    return fullPath.getAbsolutePath();
                                }
                            }
                            
                            // If we have peers connected and are downloading, the file should appear soon
                            if (numPeers > 0 && downloadRate > 0) {
                                // Short sleep to let data accumulate
                                Thread.sleep(100);
                                continue;
                            }
                        }
                        
                        loopCount++;
                        if (loopCount % 50 == 0) {
                            Log.e(TAG, "Still waiting in metadata loop, loop=" + loopCount
                                + ", elapsed=" + (System.currentTimeMillis() - startTime)/1000 + "s");
                        }
                        
                        Thread.sleep(200);
                    }
                    
                    Log.e(TAG, "Timeout waiting for file to be created: " + infoHash);
                    return null;
                }
            }
        } catch (Exception e) {
            Log.e(TAG, "Error checking initial metadata", e);
        }

        // Fallback: wait for metadata (for magnet links without .torrent file)
        long startTime = System.currentTimeMillis();
        long lastLogTime = 0;
        int fallbackLoopCount = 0;
        while (System.currentTimeMillis() - startTime < DOWNLOAD_TIMEOUT_SECONDS * 1000L) {
            if (!handle.isValid()) {
                Log.e(TAG, "Torrent handle became invalid");
                return null;
            }

            // Check status
            TorrentStatus status = handle.status();
            if (status == null) {
                Thread.sleep(500);
                continue;
            }

            TorrentStatus.State state = status.state();
            
            // Log every 3 seconds
            long now = System.currentTimeMillis();
            if (now - lastLogTime > 3000) {
                lastLogTime = now;
                Log.e(TAG, "Wait state: " + state
                    + ", hasMetadata: " + status.hasMetadata()
                    + ", numPeers: " + status.numPeers() + "/" + status.listPeers()
                    + ", numSeeds: " + status.numSeeds() + "/" + status.listSeeds()
                    + ", downloadRate: " + status.downloadRate()
                    + ", totalDone: " + status.totalDone()
                    + ", totalWanted: " + status.totalWanted());
            }

            switch (state) {
                case FINISHED:
                case SEEDING:
                case DOWNLOADING:
                    // Check if we have metadata
                    if (status.hasMetadata()) {
                        TorrentInfo ti = handle.torrentFile();
                        if (ti != null && ti.isValid() && ti.numFiles() > 0) {
                            // Get the first file path - use fileName to avoid double nesting
                            String fileName = ti.files().fileName(0);
                            File saveDir = new File(com.github.catvod.Init.context().getCacheDir(), "libtorrent/downloads");
                            File torrentDir = new File(saveDir, ti.name());
                            File fullPath = new File(torrentDir, fileName);

                            // Check if first piece is downloaded (reliable indicator of playable data)
                            if (handle.havePiece(0)) {
                                Log.e(TAG, "First piece downloaded (fallback branch): " + fullPath.getAbsolutePath());
                                return fullPath.getAbsolutePath();
                            }

                            // Log file existence for debugging
                            if (fullPath.exists() && fullPath.length() > 0) {
                                Log.e(TAG, "File exists but first piece not done yet, waiting...");
                            }
                            
                            // Log progress
                            long downloaded = status.totalDone();
                            long total = status.totalWanted();
                            if (total > 0) {
                                int pct = (int)(downloaded * 100 / total);
                                Log.e(TAG, "Progress: " + pct + "% (" + downloaded + "/" + total + " bytes)"
                                    + ", file exists=" + fullPath.exists() + ", file len=" + fullPath.length());
                            } else {
                                Log.e(TAG, "totalWanted=0, file exists=" + fullPath.exists() + ", file len=" + fullPath.length());
                            }
                            
                            // If we have download progress, the file should exist soon
                            if (downloaded > 0) {
                                Thread.sleep(100);
                                continue;
                            }
                            
                            // If totalWanted is 0 but we have metadata, the file might not be created yet
                            // Check if the save directory exists
                            if (total == 0) {
                                Log.e(TAG, "totalWanted=0, checking save dir: " + saveDir.getAbsolutePath()
                                    + " exists=" + saveDir.exists()
                                    + ", torrentDir exists=" + torrentDir.exists());
                            }
                        }
                    } else {
                        // hasMetadata is false even though we're in DOWNLOADING state
                        // This can happen for magnet links where metadata hasn't been fetched yet
                        Log.e(TAG, "DOWNLOADING but no metadata yet");
                    }
                    break;
                case DOWNLOADING_METADATA:
                    Log.e(TAG, "Still downloading metadata...");
                    break;
                case CHECKING_FILES:
                    Log.e(TAG, "Checking files...");
                    break;
                case UNKNOWN:
                case CHECKING_RESUME_DATA:
                    break;
            }

            fallbackLoopCount++;
            if (fallbackLoopCount % 20 == 0) {
                Log.e(TAG, "Fallback loop count=" + fallbackLoopCount
                    + ", elapsed=" + (System.currentTimeMillis() - startTime)/1000 + "s");
            }
            
            Thread.sleep(500);
        }

        Log.e(TAG, "Timeout waiting for download: " + infoHash);
        return null;
    }

    /**
     * Remove a torrent by info hash.
     */
    public boolean remove(String infoHash) {
        try {
            TorrentHandle handle = findTorrent(infoHash);
            if (handle != null) {
                session.swig().remove_torrent(handle.swig());
                return true;
            }
        } catch (Exception e) {
            Log.e(TAG, "Error removing torrent", e);
        }
        return false;
    }

    /**
     * Force remove a torrent.
     */
    public boolean forceRemove(String infoHash) {
        return remove(infoHash);
    }

    /**
     * Purge all download results (remove all torrents).
     */
    public boolean purgeDownloadResult() {
        try {
            org.libtorrent4j.swig.torrent_handle_vector torrents = session.swig().get_torrents();
            for (int i = 0; i < torrents.size(); i++) {
                session.swig().remove_torrent(torrents.get(i));
            }
            return true;
        } catch (Exception e) {
            Log.e(TAG, "Error purging torrents", e);
        }
        return false;
    }

    /**
     * Find a torrent handle by info hash string.
     */
    private TorrentHandle findTorrent(String infoHashHex) {
        if (infoHashHex == null || session == null) return null;
        Sha1Hash targetHash = Sha1Hash.parseHex(infoHashHex);
        if (targetHash == null) return null;
        org.libtorrent4j.swig.torrent_handle nativeHandle = session.swig().find_torrent(targetHash.swig());
        if (nativeHandle == null) return null;
        TorrentHandle handle = new TorrentHandle(nativeHandle);
        return handle.isValid() ? handle : null;
    }

    /**
     * Set file priorities for streaming: only download the first file at TOP_PRIORITY,
     * skip all others (IGNORE). Also sets the first piece deadline for faster streaming start.
     * Reference: libretorrent prioritizeFiles + setInterestedPieces
     */
    private void prioritizeForStreaming(TorrentHandle handle, TorrentInfo ti) {
        try {
            int numFiles = ti.numFiles();
            if (numFiles <= 1) {
                setFirstPiecePriority(handle, ti);
                return;
            }
            // Multi-file torrent: only download the first file, skip others
            Priority[] priorities = new Priority[numFiles];
            for (int i = 0; i < numFiles; i++) {
                priorities[i] = (i == 0) ? Priority.TOP_PRIORITY : Priority.IGNORE;
            }
            handle.prioritizeFiles(priorities);
            Log.e(TAG, "File priorities set: file[0]=TOP, others=IGNORE (" + numFiles + " files)");
            setFirstPiecePriority(handle, ti);
        } catch (Exception e) {
            Log.w(TAG, "Failed to set file priorities", e);
        }
    }

    /**
     * Set the first few pieces to TOP_PRIORITY with a deadline, ensuring the player
     * can start reading data as soon as possible.
     * Reference: libretorrent setInterestedPieces -> piecePriority(TOP) + setPieceDeadline
     */
    private void setFirstPiecePriority(TorrentHandle handle, TorrentInfo ti) {
        try {
            int numPieces = ti.numPieces();
            if (numPieces <= 0) return;
            int preloadCount = Math.min(3, numPieces);
            for (int i = 0; i < preloadCount; i++) {
                handle.piecePriority(i, Priority.TOP_PRIORITY);
                handle.setPieceDeadline(i, 2000);
            }
            Log.e(TAG, "First " + preloadCount + " pieces set to TOP_PRIORITY with 2s deadline");
        } catch (Exception e) {
            Log.w(TAG, "Failed to set first piece priority", e);
        }
    }
}
